version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  auth-service:
    build: ../App/backend/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/authdb
      - JWT_SECRET=somethingsecret
      - PORT=5001
    depends_on:
      - mongo

  product-service:
    build: ../App/backend/product-service
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/productdb
      - PORT=5002
    depends_on:
      - mongo

  order-service:
    build: ../App/backend/order-service
    container_name: order-service
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/orderdb
      - PORT=5003
    depends_on:
      - mongo

  frontend:
    build: ../App/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_API=http://auth-service:5001/api
      - REACT_APP_PRODUCT_API=http://product-service:5002/api
      - REACT_APP_ORDER_API=http://order-service:5003/api
    depends_on:
      - auth-service
      - product-service
      - order-service

volumes:
  mongodb-data: